title: Aiden McCallum #Title
logo: "images/Profile Pic.jpg" #Logo image path
description: > #Text below the picture (The br means line break or create new line)
  Programming Portfolio for Aiden McCallum <br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
